//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace printing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("printing.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string _LoginPartial_cshtml_Execute_Log_in {
            get {
                return ResourceManager.GetString("_LoginPartial_cshtml_Execute_Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string _LoginPartial_cshtml_Execute_Register {
            get {
                return ResourceManager.GetString("_LoginPartial_cshtml_Execute_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Prints.
        /// </summary>
        public static string ActivePrints {
            get {
                return ResourceManager.GetString("ActivePrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the Printing Form above to get started..
        /// </summary>
        public static string ClickTheFormAboveToGetStarted {
            get {
                return ResourceManager.GetString("ClickTheFormAboveToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Prints.
        /// </summary>
        public static string CompletedPrints {
            get {
                return ResourceManager.GetString("CompletedPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Error_cshtml_Execute_An_error_occurred_while_processing_your_request_ {
            get {
                return ResourceManager.GetString("Error_cshtml_Execute_An_error_occurred_while_processing_your_request_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_cshtml_Execute_Error {
            get {
                return ResourceManager.GetString("Error_cshtml_Execute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the selected file. Please provide a valid .PNG file and try again..
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Form.
        /// </summary>
        public static string Form_cshtml_Execute_Form {
            get {
                return ResourceManager.GetString("Form_cshtml_Execute_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to insert a print..
        /// </summary>
        public static string Form_cshtml_Execute_Use_this_area_to_insert_a_print_ {
            get {
                return ResourceManager.GetString("Form_cshtml_Execute_Use_this_area_to_insert_a_print_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FormViewModel_Field2_Field2 {
            get {
                return ResourceManager.GetString("FormViewModel_Field2_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FormViewModel_Field3_Field3 {
            get {
                return ResourceManager.GetString("FormViewModel_Field3_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File (.PNG).
        /// </summary>
        public static string FormViewModel_File_File {
            get {
                return ResourceManager.GetString("FormViewModel_File_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid integer number..
        /// </summary>
        public static string FormViewModel_ID_Please_enter_a_valid_integer_number_ {
            get {
                return ResourceManager.GetString("FormViewModel_ID_Please_enter_a_valid_integer_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass (1-60).
        /// </summary>
        public static string FormViewModel_Mass_Mass__1_60_ {
            get {
                return ResourceManager.GetString("FormViewModel_Mass_Mass__1_60_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid integer number..
        /// </summary>
        public static string FormViewModel_Mass_Please_enter_a_valid_integer_number_ {
            get {
                return ResourceManager.GetString("FormViewModel_Mass_Please_enter_a_valid_integer_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Date.
        /// </summary>
        public static string FormViewModel_PostedDate {
            get {
                return ResourceManager.GetString("FormViewModel_PostedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string FormViewModel_PrintPriority_Priority {
            get {
                return ResourceManager.GetString("FormViewModel_PrintPriority_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all completed prints as XML.
        /// </summary>
        public static string Get_All_Prints {
            get {
                return ResourceManager.GetString("Get_All_Prints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get this Print as XML.
        /// </summary>
        public static string GetPrintAsXML {
            get {
                return ResourceManager.GetString("GetPrintAsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to view your past prints..
        /// </summary>
        public static string HistoryDescription {
            get {
                return ResourceManager.GetString("HistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with form validation. Please try again..
        /// </summary>
        public static string HomeController_Form_An_error_occurred_with_form_validation__Please_try_again_ {
            get {
                return ResourceManager.GetString("HomeController_Form_An_error_occurred_with_form_validation__Please_try_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print successfully saved! You can find more details about that print in your mailbox..
        /// </summary>
        public static string HomeController_Form_Print_successfully_saved__You_can_invoke_the_Service_with_your_ID__ {
            get {
                return ResourceManager.GetString("HomeController_Form_Print_successfully_saved__You_can_invoke_the_Service_with_you" +
                        "r_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Index_cshtml_Execute_Home_Page {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginViewModel_Email_Email {
            get {
                return ResourceManager.GetString("LoginViewModel_Email_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewModel_Password_Password {
            get {
                return ResourceManager.GetString("LoginViewModel_Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LoginViewModel_RememberMe_Remember_me_ {
            get {
                return ResourceManager.GetString("LoginViewModel_RememberMe_Remember_me_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused Prints.
        /// </summary>
        public static string PausedPrints {
            get {
                return ResourceManager.GetString("PausedPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place in queue.
        /// </summary>
        public static string PlaceInQueue {
            get {
                return ResourceManager.GetString("PlaceInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the boxes below..
        /// </summary>
        public static string Please_Fill_The_Boxes_Below {
            get {
                return ResourceManager.GetString("Please_Fill_The_Boxes_Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsANewUser {
            get {
                return ResourceManager.GetString("RegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterViewModel_ConfirmPassword_Confirm_password {
            get {
                return ResourceManager.GetString("RegisterViewModel_ConfirmPassword_Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string RegisterViewModel_ConfirmPassword_The_password_and_confirmation_password_do_not_match_ {
            get {
                return ResourceManager.GetString("RegisterViewModel_ConfirmPassword_The_password_and_confirmation_password_do_not_m" +
                        "atch_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterViewModel_Email_Email {
            get {
                return ResourceManager.GetString("RegisterViewModel_Email_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterViewModel_Password_Password {
            get {
                return ResourceManager.GetString("RegisterViewModel_Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RegisterViewModel_Password_The__0__must_be_at_least__2__characters_long_ {
            get {
                return ResourceManager.GetString("RegisterViewModel_Password_The__0__must_be_at_least__2__characters_long_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints.
        /// </summary>
        public static string Service_cshtml_Execute_Service {
            get {
                return ResourceManager.GetString("Service_cshtml_Execute_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to view your active prints..
        /// </summary>
        public static string Service_cshtml_Execute_Use_this_area_to_get_a_print_by_its_id_or_get_all_prints_ {
            get {
                return ResourceManager.GetString("Service_cshtml_Execute_Use_this_area_to_get_a_print_by_its_id_or_get_all_prints_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stranger.
        /// </summary>
        public static string Stranger {
            get {
                return ResourceManager.GetString("Stranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3d Printing Prints.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts in / Remaining (minutes).
        /// </summary>
        public static string TimeToStart {
            get {
                return ResourceManager.GetString("TimeToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to continue..
        /// </summary>
        public static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
